
services:
  db:
    image: postgres:15
    container_name: casalivraison_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ayoub300696
      POSTGRES_DB: casalivraison
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: casalivraison_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: npm run dev

volumes:
  postgres_data:
